- ExampleScript.py
- parametric_stellarator.py
- source_mesh.py
Adds ability to model a source mesh based on plasma equilibrium data. The mesh is structured in confinement space and transformed to a tetrahedral mesh in real space.
> Add source mesh modeling

- ExampleScript.py
- NWL/NWL.py
- NWL/NWL_geom.py
- NWL/NWL_plot.py
- NWL/NWL_transport.py
- magnet_coils.py
- parastell.py
- source_mesh.py
Adds a script to compute NWL and create all corresponding geometry, source, etc. For now, this functionality is included in a separate directory but this organization is free to change. Note that there are three primary functionalities in the main script `NWL.py`, reflected by the three new example scripts `NWL_geom.py`, `NWL_transport.py`, and `NWL_plot.py`. We should discuss this structure but it is primarily due to the (not strict) necessity of separate `conda` environments for ParaStell and OpenMC. Cubit (a dependency of ParaStell) is built with an HDF5 version that does not play well with `conda` environments containing OpenMC. Perhaps there is some solution we can figure out that would remedy this issue.
Fixes #22
> Add support for NWL calculations

- magnet_coils.py
Very small PR to fix a typo in the magnet STEP export. Accidentally omitted a "." in the magnet STEP file export path.
> Fix typo in magnet STEP export

- .gitignore
- README.md
- config.yaml
- example.py
Included Yaml input file and new python execution file. Current issue with getting to write to a yaml output file. Will likely be updated depending on how strengths output changes.
Closes #45
> Yamlification of parastell

- src/cubit_io.py
- src/invessel_build.py
- src/magnet_coils.py
- src/parastell.py
- src/source_mesh.py
- src/utils.py
- tests/test_invessel_build.py
- tests/test_magnet_coils.py
- tests/test_parastell.py
- tests/test_source_mesh.py
Here are a number of changes to the latest update to streamline a number of things.  I used a number of small commits to show the individual changes, mostly distinct from each other. NOTE: this PR will update the `ivc_oo` branch thus changing PR #55 
None of this has been tested since I don't have a robust testing environment for the whole process, so there may be some typo bugs.
* use a more conventional singleton pattern for cubit initialization
* move the defaults to be members of utils rather than returned by a function
* don't overuse try/raise blocks
* make IVB.Surfaces and IVB.Components into dictionaries based on their name since we need this info together often
* put module imports in a more pythonic order - native modules to third party modules to custom dependencies to local …
> Some final input on the IVC OO update

- INSTALL.md
- README.md
- environment.yml
Rewrites the installation instructions to reflect updates to dependencies. Also streamlines the installation process to reduce the number of steps. Confirmed to work with a new Conda test environment.
Closes #62.
> Update installation documentation

- dockerfile
- environment.yml
Heavily inspired by a dockerfile shared by Shimwell here https://forum.coreform.com/t/trelis-in-docker/442/2.
Uses the miniconda docker image as the base (Debian Bullseye), found here https://hub.docker.com/r/continuumio/miniconda3. To use cubit, the image can be run interactively, and the license file copied to the appropriate location. Cubit works in terminal with the --no-graphics option and can be imported into python. 
I expect it will need a couple additions for this to work with Github actions. I'll start looking at that documentation in the next few days, in the meantime wanted to get this posted to get some eyes on it sooner rather than later
fixes #57
> Add dockerfile

- README.md
Updates details about dependencies in the installation instructions on `main`.
The installation instructions did not accurately reflect ParaStell's Python dependencies. Additional Python dependencies have been added.
Furthermore, this changes installation instructions for PyStell-UW to specify cloning the `old` branch. There are several issues with the `master` branch of PyStell-UW that prevent its successful integration with ParaStell.
> Update installation instructions on `main`

- NWL/NWL.py
- NWL/NWL_geom.py
- NWL/NWL_plot.py
- NWL/NWL_transport.py
Calculates the area of each bin by converting the corners to xyz and approximating the area as 2 triangles.
The following plot was generated using NWL_plot.py, and a surface source with a million particles.
Importing the points in `bin_arr` to cubit and overlaying on the geometry it can be seen that they align nicely with the geometry, with half size bins at the toroidal and poloidal extent edges
The area from summing `area_array` for the parameters in NWL_plot.py is 228.97m2, and measuring in cubit the area is 229.00 m2.
Fixes #23
> added area normalization to NWL.py

- parastell.py
Great to see cad-to-dagmc getting some use. I've been working on that package recently and have made a few releases and improvement
the latest version is 0.6.2 and it moves the material tag to the export call. this was done to allow users to add cad and export to gmsh meshes or unstructured dagmc meshes without needing to give material tags (as they would not be used.
Sorry for the breaking changes.
> updated cad-to-dagmc API usage for v0.6.2 compatability

- README.md
- parastell.py
Updates syntax in ParaStell's `main` branch to reflect recent updates to its dependency, PyStell-UW.
Closes #72.
> Update integration with PyStell-UW on `main`

- parastell/invessel_build.py
- tests/test_invessel_build.py
Fixes a typo in the `export_cad_to_dagmc` method of `InVesselBuild` and incorporates that method in `test_invessel_build.py`.
Closes #87.
> Fix Typo in `InVesselBuild` and Incorporate CAD-to-DAGMC in Testing

- NWL/NWL.py
The full function may take a long time to run, and it would be convenient to be able to avoid needing to rerun the entire function in order to iterate plots.
Closes #90 
Perhaps it would be better to split the NWL_plot into two functions, one that makes the NWL matrix and one that plots it?
> return parameters used to plot NWL from NWL_plot

- parastell/invessel_build.py
- parastell/log.py
- parastell/magnet_coils.py
- parastell/parastell.py
- parastell/source_mesh.py
Adds a pseudo logger class, `NullLogger`, with some of the same class methods as the built-in Python `logging` class object, but whose methods do nothing when called.
The purpose of `NullLogger` is to streamline ParaStell code but not enforce logging when using the Python API. A logger does get enforced upon the user when using the command-line interface with YAML input.
Depends on #85.
Closes #46.
> Introduce Null Logger Class

- .gitignore
- parastell/invessel_build.py
- parastell/magnet_coils.py
- parastell/parastell.py
- parastell/source_mesh.py
- parastell/utils.py
As I started looking at implementing NWL in the OO version, I realized that we were kind of heavy-handed with kwargs. I think this finds a better balance. Let me know what you think.
Some explanations for the changes:
1. The old code had the lists of allowable arguments defined in multiple places.  They should be defined in as few places as possible - ideally only one.
2. Most of the uses of `construct_kwargs_from_dict` were for passing into a constructor for some class.  That class is the best place to know what arguments are allowable, so its best to pass in the whole dictionary and then cherry-pick relevant data in the constructor.
3. `set_kwarg_attrs` was the function that cherry-picked from the dictionary, but raised exceptions by default for extra arguments.  We probably discussed …
> Streamline kwargs

- parastell/nwl_utils.py
The matrix returned by `numpy.historgram2d` in `nwl_utils.py` has rows corresponding to our toroidal angles and columns corresponding to our poloidal angles. However, when we plot the NWL, we set our x-axis to our toroidal angles and our y-axis to our poloidal angles, which is the reverse of the NWL matrix. This PR transposes the NWL matrix such that its rows and columns correspond to the x- and y-axes appropriately.
> Fix NWL plot

- parastell/invessel_build.py
At some point, CadQuery's syntax to union solids together changed from `Component.union(...)` to `Component.fuse(...)`. This PR updates ParaStell's syntax to reflect that change.
> Update syntax to union repeated component segments

- Examples/config.yaml
- Examples/parastell_example.py
- parastell/cubit_io.py
- parastell/parastell.py
- tests/test_parastell.py
see #111, trying again but from a branch on the upstream to hopefully pass CI
closes #93
> add option to export to cub5 

- Dockerfile
The Build & publish Docker image for ParaStell CI action currently is failing since `apt-get` cannot find libtiff5. I noticed the base image had updated just prior to this failure, and tried with tag for the previous docker image which resolved the missing library issue.
Fixes #115
> resolve missing library when building dockerfile

- parastell/magnet_coils.py
Currently, the logic for building magnet coils assumes that all filaments in the coils file have an equal number of points. When trying to use parastell on a coils file for W7-X, I found that the filaments don't have the same length (namely, non-planar and planar coils for W7-X have a different number of points). This PR updates the logic around storing filaments data and computing an average radial distance to accommodate having a variable number of points per filament.
> Allow coil filaments to have variable number of points

- .github/workflows/ci.yml
- Dockerfile
- README.md
- parastell/invessel_build.py
- parastell/nwl_utils.py
- parastell/parastell.py
- parastell/source_mesh.py
- tests/test_invessel_build.py
- tests/test_source_mesh.py
Right now, imports to pystell are of the form `import src.pystell`. This appears to be the case because pystell uses a `src` directory as the root for its Python package. So, if you add the root directory of the pystell git repository to your `PYTHONPATH`, the imports work correctly. However, pystell has a pyproject.toml file that should be used rather than manipulating the `PYTHONPATH` environment variable. Specifically, pystell can be installed by simply running `pip install git+https://github.com/aaroncbader/pystell_uw.git`.
> Assume pystell is installed properly in Python environment

- Examples/nwl_geom_example.py
Updates the DAGMC export portion of `nwl_geom_example.py` to reflect the new ParaStell workflow and include the `build_cubit_model` method of the `Stellarator` class.
> Update DAGMC export in `nwl_geom_example.py`

- Examples/nwl_plot_example.py
- parastell/nwl_utils.py
> Parallelize nwl

- Examples/custom_source_example.py
- parastell/parastell.py
- parastell/source_mesh.py
- parastell/utils.py
This PR will allow users to pass custom functions for plasma conditions and reaction rates as keyword arguments to either `Stellarator` or `SourceMesh`. The default behavior is to use the same plasma condition/reaction rate that it always has.
The plasma conditions function takes only one input, the plasma parameter s, and must return whatever inputs are required by the reaction rate function. The reaction rate function should return a single value.
Here's an example where the source strengths follow a sine profile:
Should I extend the parastell_example.py script to include an example of creating a custom source definition as well?
Addresses #51
> Add ability to provide custom source strength functions

- .github/workflows/black.yml
- Examples/custom_source_example.py
- Examples/nwl_geom_example.py
- Examples/parastell_example.py
- parastell/cubit_io.py
- parastell/invessel_build.py
- parastell/log.py
- parastell/magnet_coils.py
- parastell/parastell.py
- parastell/source_mesh.py
- parastell/utils.py
- tests/test_magnet_coils.py
- tests/test_parastell.py
- tests/test_source_mesh.py
Two things.
1. `black --line-length 79  .` was run to format all python files with black, and with a line length of 79 characters, per PEP8. Black by default uses 88.
2. An action that checks that code has been formatted such that applying `black --line-length 79  .` does not result in any changes has been added. It runs on pushes, PRs, and manaully.
When/if a `pyproject.toml` is authored it should include black args, and the action should be updated to reference `pyproject.toml`, rather than including the necessary args in the yaml file.
> Black autoformatting

- parastell/invessel_build.py
- parastell/parastell.py
There is some ambiguity about the behavior of `split_chamber`, especially related to how the inserted `"chamber"` component uses any `thickness_matrix` input. This updates documentation to hopefully make that behavior more transparent.
Closes #144.
> Update documentation to clarify behavior of `split_chamber`

- Examples/config.yaml
- Examples/parastell_example.py
- parastell/magnet_coils.py
- parastell/parastell.py
- tests/test_magnet_coils.py
- tests/test_parastell.py
Models the magnets using CadQuery instead of Coreform Cubit. Furthermore, restricts magnet cross-section to rectangular, removing the option for circular magnets.
Closes #138
> Change magnet modeling workflow to use CadQuery

- environment.yml
- parastell/nwl_utils.py
With the newest version of openmc (0.15.0) the previous conflict with Cubit seems to have been resolved. The remaining conflict with matplotlib can be resolved as in this PR, allowing the full NWL workflow to be performed in one script. In a future PR the nwl_utils example could be updated to be a single script.
> Use non-interactive backend in nwl utils to avoid matplotlib cubit conflict

- Examples/radial_build_distance_example.py
- parastell/radial_distance_utils.py
This is a relatively concentrated hot fix that updates the radial distance utility to reflect recent changes to the syntax of the magnet workflow. Changes include:
- Syntax updates in the `radial_distance_utils.get_reordered_filaments` function.
- A condition added to the `radial_distance_utils.reorder_filaments` function to better address edge cases encountered during testing.
- Modifications to the example script
- Reflect changes to the `MagnetSet` class
- Reference input files actually present in the `Examples` directory
- Modify the `RadialBuild` and `InVesselBuild` class instantiations to reflect proper use.
The scope of this PR was kept relatively focused but additional changes should be made to the radial distance utility in subsequent PRs to better leverage modifications to the …
> Radial distance utility hot fix

- Examples/radial_build_distance_example.py
- parastell/magnet_coils.py
- parastell/parastell.py
- parastell/radial_distance_utils.py
- tests/test_magnet_coils.py
Streamlines and reorganizes use of filament coordinate data as follows:
- Instantiates a new `MagnetCoil` class object as filament coordinate data becomes available in the `MagnetSet._instantiate_coils` method (formerly named `MagnetSet._extract_filament_data`), rather than store all filament data separately (and redundantly) in the `MagnetSet` class.
- For the purpose of filtering coils based on toroidal angle, moves the check of whether each coil lies within the model's toroidal extent to the `check_coil_toroidal_extent` method of the `MagnetCoil` class, rather than the `_filter_coils` method of the `MagnetSet` class (formerly named `MagnetSet._filter_filaments`). The `MagnetCoil._check_coil_toroidal_extent` method is called by the `MagnetSet._filter_coils` method to subsequently …
> Refactor filament data use

- Examples/nwl_geom_example.py
- parastell/cubit_io.py
- parastell/nwl_utils.py
Updates the example to apply a vacuum boundary condition prior to DAGMC export. Fixes #155. Tried to make this as minimal of a fix as possible
> use UWUW vacuum boundary condition for NWL example

- .github/workflows/docker_publish.yml
Currently, `docker_publish.yml` pulls and pushes docker images to a hardcoded image name and tag, which is the official parastell docker image. This can be problematic if a branch changes something and pushes a docker image that doesn't work.
I have changed `docker_publish.yml` to now pull and push docker images to the same image name, but with a tag based on the branch name if the branch is not `main`. This way, contributors can make changes without worrying about breaking the official image. 
This PR is a continuation of #154, with the difference being that this PR was pushed to a branch in the repo owned by `svalinn` instead of a branch in my forked repo.
> Add tags to docker images to prevent branches from overwriting Parastell docker images

- parastell/parastell.py
It is convenient to have the cell ids start at 1 with the plasma chamber, makes it more obvious which cells will be which in openmc
> import ivb components first so vol ids start at 1

- parastell/invessel_build.py
- parastell/nwl_utils.py
I experienced an error with nwl_utils.py as currently written, since theta_coords is a list. This approach, or changing theta_coords to a numpy array will alleviate that error.
Fixed a missing comma in invessel_build.py
> Use list comprehension for shift the theta coordinate from 0 to 2pi

- parastell/cubit_io.py
- parastell/invessel_build.py
- parastell/magnet_coils.py
- parastell/parastell.py
- tests/test_magnet_coils.py
- tests/test_parastell.py
Makes the following changes in an effort to improve the magnet meshing workflow, as well as fix some oversights in a previous PR:
- Changes magnet meshing algorithm in Cubit to one that gives greater control over mesh parameters, adding additional meshing arguments
- Puts checks in magnet meshing workflow to determine whether magnets have already been imported into Cubit, and if not, to properly set volume IDs
- Modifies magnet meshing call in Stellarator class to incorporate additional meshing arguments
- Moves magnet and IVB STEP imports in Cubit to corresponding objects
- Updates magnet STEP import in Cubit to properly set volume IDs, reflecting recent changes in STEP import order
- Updates tests to check that volume IDs are properly set
> Modify and update magnet meshing workflow

- parastell/source_mesh.py
- tests/test_source_mesh.py
Corrects implementation of MOAB canonical ordering. Changes are as follows:
- Changes MOAB canonical ordering for both wedges and hexahedra to coincide with element splitting shown in ParaStell publication (Moreno, Bader, Wilson, 2024)
- Adds documentation explaining MOAB canonical ordering for posterity
Closes #166
> Fix MOAB canonical ordering during element splitting

- parastell/source_mesh.py
- tests/test_parastell.py
- tests/test_source_mesh.py
Modifies the source mesh workflow to alternate the scheme by which hexahedra and wedges are split into tetrahedra. The alternating schemes ensure that the faces of adjacent tetrahedra, but not belonging to the same hexahedron or wedge, match one another. This avoids gaps and overlaps between adjacent non-planar hexahedron and wedge faces. This alignment is ensured for adjacent wedge-wedge, wedge-hexahedron, and hexahedron-hexahedron pairs. Code changes are as follows:
- Introduces `alternate_scheme`, `toroidal_alt_scheme`, and `cfs_alt_scheme` boolean parameters to control whether an alternate division scheme should be used for a given element
- Introduces an alternate division scheme, in the form of MOAB canonical indices defining the tetrahedral division of a given element, for both …
> Implement alternating division schemes between adjacent hexahedra and wedges

- environment.yml
Adds a specification for the version of CAD-to-DAGMC in the conda environment file. The specified versions are greater than or equal to [version 0.7.5](https://github.com/fusion-energy/cad_to_dagmc/releases/tag/0.7.5), in which the imprint operation was changed to being optional. This PR is intended to be merged before #180.
> Add specification for CAD-to-DAGMC version

- .github/workflows/ci.yml
- .github/workflows/docker_publish.yml
- Dockerfile
- Examples/config.yaml
- Examples/nwl_geom_example.py
- Examples/parastell_example.py
- Examples/radial_distance_example.py
- README.md
- parastell/cubit_io.py
- parastell/parastell.py
Updates syntax and documentation to integrate the latest version of Cubit (version 2024.8). In addition, removes all legacy DAGMC functionality in Cubit as it is no longer supported in more recent versions.
> Update Cubit Version

- environment.yml
Adds PyDAGMC to the testing environment. #190 depends on PyDAGMC.
> add pydagmc to environment

- environment.yml
Updates the CAD-to-DAGMC version specified in the Conda environment file to be newer than or equal to 0.8.2 in order to incorporate API changes.
> Update CAD-to-DAGMC version in Conda environment file

- parastell/parastell.py
- tests/test_parastell.py
This branch modifies the open-source DAGMC workflow such that an in-memory `cadquery.Compound` object, comprising all IVB and magnet solids, is directly supplied directly to Gmsh, leveraging CAD-to-DAGMC's utility functions. This workflow skips imprinting, since it is not necessary for valid ParaStell geometries. This workflow also circumvents a merging routine since in-memory CAD solids are already "merged" (i.e., coincident surfaces are already shared between adjacent solids) due to the manner by which we create our IVB CAD solids (cutting interior components away).
> Fix open-source DAGMC workflow

- parastell/utils.py
Modifies `utils.expand_list` to add entries only when `num > len(list)`, and otherwise preserve the original list, which is the expected behavior. I discovered that if `num < len(list)` the resultant `list_exp` could be different than the input `list`.
> Modify `utils.expand_list` to only conditionally add entries

- parastell/parastell.py
This PR adds the option to define a custom export directory for the dagmc model created with pydagmc.
Closes #199 .
> adds custom export directory to export_pydagmc_model method

- parastell/invessel_build.py
- parastell/utils.py
- tests/test_parastell.py
- tests/test_utils.py
Updates to use the new import name for pydagmc.
Closes #211
Tests should be failing currently, when https://github.com/svalinn/pydagmc/pull/31 gets merged, we should be able to update the CI image and see that tests will be passing.
> update to import pydagmc

- .github/workflows/docker_publish.yml
Since the PyDAGMC change did not affect any of the inputs to the docker image, I believe that the cached version was used when I manually triggered the CI image to build.
If I did everything right, this PR should make it so the CI image will be built with no cache when the workflow is triggered manually. This will take a bit longer for manual runs, but will ensure that we get a build with all the latest quirks and features when triggering manually.
> Make manually triggered workflow use no cache

- Examples/custom_first_wall_profile_example.py
- Examples/custom_source_example.py
- Examples/parastell_cad_to_dagmc_example.py
- Examples/parastell_cubit_example.py
- Examples/parastell_pydagmc_example.py
- Examples/radial_distance_example.py
- parastell/cubit_utils.py
- parastell/invessel_build.py
- parastell/magnet_coils.py
- parastell/parastell.py
- parastell/source_mesh.py
- parastell/utils.py
- tests/test_invessel_build.py
- tests/test_magnet_coils.py
- tests/test_parastell.py
- tests/test_source_mesh.py
This branch introduces open-source tetrahedral meshing workflows for the `InVesselBuild` and `MagnetSet` classes.
The `InVesselBuild` class has two meshing routines added, one using MOAB and another using Gmsh.
- The MOAB routine, analogous to the PyDAGMC workflow, uses the IVB point cloud to generate a mesh in MOAB for a single specified component. In the resulting mesh, the component is one tetrahedron thick. In fact, one purpose of this MOAB workflow is to ensure a one-tetrahedron-thick mesh (useful for mesh tallies). This capability may be expanded to include multiple components in a single mesh.
- The Gmsh routine is usable with both CadQuery and PyDAGMC geometries. When used in conjunction with CadQuery geometries, CadQuery CAD solids are directly imported and meshed. When used with …
> Add open-source volumetric meshing routines

- Examples/radial_distance_example.py
- parastell/parastell.py
- parastell/radial_distance_utils.py
The radial distance utility was not updated to accommodate API changes from #198. This fixes that issue.
> Update radial distance utility to accommodate recent API changes

- environment.yml
- parastell/parastell.py
Updates use of CAD-to-DAGMC's API for versions 0.9.1+ and pins those versions in the conda environment file.
Closes #227
> Update syntax for newer versions of CAD-to-DAGMC

- parastell/invessel_build.py
- tests/test_parastell.py
Adds support for modeling continuous, 360-degree geometries for the PyDAGMC workflow (note that continuous geometries were already supported in the CAD-based workflow using the `repeat` parameter). Also adds a test to `test_parastell.py` to check this functionality.
> Add support for continuous, 360-degree geometries in PyDAGMC workflow

- parastell/invessel_build.py
- parastell/parastell.py
- tests/test_invessel_build.py
- tests/test_parastell.py
Enables the generation of meshes including multiple components for the MOAB workflow. This workflow avoids repeated vertices for adjacent components while supporting gaps from excluded components.
> Add support for multi-component IVB meshes using the MOAB workflow

- parastell/parastell.py
A quick hotfix to update documentation reflecting recent API changes to `export_invessel_build_mesh_moab`
> Update documentation for IVB MOAB meshing routine

- environment.yml
Relaxes the dependencies specified in `environment.yml`. One major change is that we no longer require a specific version of Python
> Relax dependencies

- parastell/invessel_build.py
This branch removes the call for Gmsh to delete duplicate nodes in the PyDAGMC-Gmsh routine. This fixes a recently discovered issue that OpenMC can have a hard time loading such meshes for some of its functionality.
`gmsh.model.mesh.removeDuplicateNodes()` was used to try to reduce mesh file size but is not strictly necessary. My guess is that Gmsh may have just been removing those nodes it deemed duplicates without actually replacing the entities for the associated tetrahedra
> Don't remove duplicate nodes in PyDAGMC-Gmsh routine

- parastell/invessel_build.py
Changes the calculation of poloidal profile tangents, used to compute IVB surface normals, in the following ways:
- Handle calculation differently for VMEC and rib-based surfaces. Specifically, the poloidal perturbation is made larger for rib-based surfaces. It was found during testing that the perturbation used for VMEC surfaces, 1e-4, was small for the interpolator and gave unexpected results.
- Migrate the calculation to the respective classes, similar to `angles_to_xyz`, in the form of a new class method `calculate_tangents`
- Modify the calculation to use a central difference, rather than a forward difference
> Modify calculation of poloidal profile tangents

- parastell/invessel_build.py
- parastell/magnet_coils.py
Makes Gmsh use all available threads for meshing, rather than using just a single thread
> Multithread Gmsh meshing

- parastell/magnet_coils.py
Previously, some coil geometries (depending on how they were created) were imported as stored as a single `cq.Compound` object, rather than as a list of `cq.Solid` objects. This caused material assignments for imported magnet geometries to fail for the CAD-to-DAGMC workflow.
> Fix storage of coil solids for imported geometries

- .github/workflows/ci.yml
- .github/workflows/docker_publish.yml
Adds a command in the CI workflow files to log out of Cubit's RLM server after tests are run
> Log out of license server after CI tests

- parastell/magnet_coils.py
This branch modifies the magnet creation workflow such that when `toroidal_extent = 360.0`, the intersection operation of each magnet coil with `toroidal_domain` does not occur. This does not cause any issues, but is an unnecessary operation.
> Change handling of 360-degree geometries for magnets

- parastell/magnet_coils.py
- parastell/parastell.py
- tests/test_parastell.py
Automates the process of assigning volume IDs to imported magnet geometries, by detecting nested volume pairs, rather than relying on the user to provide them. The tests written as-is should be sufficient to detect any issues with this new routine.
Also adds an imprinting routine for nested magnet geometries, to ensure that imported geometries have shared CAD surfaces for CAD-to-DAGMC and Gmsh routines.
> Automate volume ID assignment for imported magnet geometries and imprint

- parastell/magnet_coils.py
Not to make the volume ID assignment algorithm more of a beast, but I realized in testing that the condition for evaluating the closeness of solids was insufficient for geometries that are cut at the ends of the toroidal domain of the model. In such cases, the toroidal angles of the centers of mass of the cut solids tend to be quite close to each other. To solve this issue, I added a radial component to the evaluation.
> Add radial component to closeness evaluation
